/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sdegaonk' at '4/21/17 11:39 AM' with Gradle 2.14.1
 *
 * @author sdegaonk, @date 4/21/17 11:39 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
